CREATE TYPE public.e_continent AS ENUM('Africa', 'Antarctica', 'Asia', 'Europe', 'Oceania', 'North America', 'South America');
CREATE TABLE public.countries (
    id text NOT NULL,
    name text NOT NULL,
    continent public.e_continent NOT NULL,
    PRIMARY KEY (id)
);
INSERT INTO public.countries(id, name, continent)
VALUES
 ('AW', 'Aruba', 'North America'),
 ('AF', 'Afghanistan', 'Asia'),
 ('AO', 'Angola', 'Africa'),
 ('AI', 'Anguilla', 'North America'),
 ('AX', 'Aland Islands', 'Europe'),
 ('AL', 'Albania', 'Europe'),
 ('AD', 'Andorra', 'Europe'),
 ('AN', 'Netherlands Antilles', 'North America'),
 ('AE', 'United Arab Emirates', 'Asia'),
 ('AR', 'Argentina', 'South America'),
 ('AM', 'Armenia', 'Asia'),
 ('AS', 'American Samoa', 'Oceania'),
 ('AQ', 'Antarctica', 'Antarctica'),
 ('TF', 'French Southern Territories', 'Antarctica'),
 ('AG', 'Antigua and Barbuda', 'North America'),
 ('AU', 'Australia', 'Oceania'),
 ('AT', 'Austria', 'Europe'),
 ('AZ', 'Azerbaijan', 'Asia'),
 ('BI', 'Burundi', 'Africa'),
 ('BE', 'Belgium', 'Europe'),
 ('BJ', 'Benin', 'Africa'),
 ('BF', 'Burkina Faso', 'Africa'),
 ('BD', 'Bangladesh', 'Asia'),
 ('BG', 'Bulgaria', 'Europe'),
 ('BH', 'Bahrain', 'Asia'),
 ('BS', 'Bahamas', 'North America'),
 ('BA', 'Bosnia and Herzegovina', 'Europe'),
 ('BY', 'Belarus', 'Europe'),
 ('BZ', 'Belize', 'North America'),
 ('BM', 'Bermuda', 'North America'),
 ('BO', 'Bolivia', 'South America'),
 ('BR', 'Brazil', 'South America'),
 ('BB', 'Barbados', 'North America'),
 ('BN', 'Brunei Darussalam', 'Asia'),
 ('BT', 'Bhutan', 'Asia'),
 ('BV', 'Bouvet Island', 'Antarctica'),
 ('BW', 'Botswana', 'Africa'),
 ('CF', 'Central African Republic', 'Africa'),
 ('CA', 'Canada', 'North America'),
 ('CC', 'Cocos Islands', 'Asia'),
 ('CH', 'Switzerland', 'Europe'),
 ('CL', 'Chile', 'South America'),
 ('CN', 'China', 'Asia'),
 ('CI', 'Cote dIvoire', 'Africa'),
 ('CM', 'Cameroon', 'Africa'),
 ('CG', 'Congo', 'Africa'),
 ('CD', 'Congo (Democratic Republic of the)', 'Africa'),
 ('CK', 'Cook Islands', 'Oceania'),
 ('CO', 'Colombia', 'South America'),
 ('KM', 'Comoros', 'Africa'),
 ('CV', 'Cape Verde', 'Africa'),
 ('CR', 'Costa Rica', 'North America'),
 ('CU', 'Cuba', 'North America'),
 ('CX', 'Christmas Island', 'Asia'),
 ('KY', 'Cayman Islands', 'North America'),
 ('CY', 'Cyprus', 'Asia'),
 ('CZ', 'Czech Republic', 'Europe'),
 ('DE', 'Germany', 'Europe'),
 ('DJ', 'Djibouti', 'Africa'),
 ('DM', 'Dominica', 'North America'),
 ('DK', 'Denmark', 'Europe'),
 ('DO', 'Dominican Republic', 'North America'),
 ('DZ', 'Algeria', 'Africa'),
 ('EC', 'Ecuador', 'South America'),
 ('EG', 'Egypt', 'Africa'),
 ('ER', 'Eritrea', 'Africa'),
 ('EH', 'Western Sahara', 'Africa'),
 ('ES', 'Spain', 'Europe'),
 ('EE', 'Estonia', 'Europe'),
 ('ET', 'Ethiopia', 'Africa'),
 ('FI', 'Finland', 'Europe'),
 ('FJ', 'Fiji', 'Oceania'),
 ('FK', 'Falkland Islands', 'South America'),
 ('FR', 'France', 'Europe'),
 ('FO', 'Faroe Islands', 'Europe'),
 ('FM', 'Micronesia', 'Oceania'),
 ('GA', 'Gabon', 'Africa'),
 ('GB', 'United Kingdom', 'Europe'),
 ('GE', 'Georgia', 'Asia'),
 ('GG', 'Guernsey', 'Europe'),
 ('GH', 'Ghana', 'Africa'),
 ('GI', 'Gibraltar', 'Europe'),
 ('GN', 'Guinea', 'Africa'),
 ('GP', 'Guadeloupe', 'North America'),
 ('GM', 'Gambia', 'Africa'),
 ('GW', 'Guinea-Bissau', 'Africa'),
 ('GQ', 'Equatorial Guinea', 'Africa'),
 ('GR', 'Greece', 'Europe'),
 ('GD', 'Grenada', 'North America'),
 ('GL', 'Greenland', 'North America'),
 ('GT', 'Guatemala', 'North America'),
 ('GF', 'French Guiana', 'South America'),
 ('GU', 'Guam', 'Oceania'),
 ('GY', 'Guyana', 'South America'),
 ('HK', 'Hong Kong', 'Asia'),
 ('HM', 'Heard Island and McDonald Islands', 'Antarctica'),
 ('HN', 'Honduras', 'North America'),
 ('HR', 'Croatia', 'Europe'),
 ('HT', 'Haiti', 'North America'),
 ('HU', 'Hungary', 'Europe'),
 ('ID', 'Indonesia', 'Asia'),
 ('IM', 'Isle of Man', 'Europe'),
 ('IN', 'India', 'Asia'),
 ('IO', 'British Indian Ocean Territory', 'Asia'),
 ('IE', 'Ireland', 'Europe'),
 ('IR', 'Iran', 'Asia'),
 ('IQ', 'Iraq', 'Asia'),
 ('IS', 'Iceland', 'Europe'),
 ('IL', 'Israel', 'Asia'),
 ('IT', 'Italy', 'Europe'),
 ('JM', 'Jamaica', 'North America'),
 ('JE', 'Jersey', 'Europe'),
 ('JO', 'Jordan', 'Asia'),
 ('JP', 'Japan', 'Asia'),
 ('KZ', 'Kazakhstan', 'Asia'),
 ('KE', 'Kenya', 'Africa'),
 ('KG', 'Kyrgyzstan', 'Asia'),
 ('KH', 'Cambodia', 'Asia'),
 ('KI', 'Kiribati', 'Oceania'),
 ('KN', 'Saint Kitts and Nevis', 'North America'),
 ('KP', 'Korea(Democratic People Republic of)', 'Asia'),
 ('KW', 'Kuwait', 'Asia'),
 ('LA', 'Lao Peoples Democratic Republic', 'Asia'),
 ('LB', 'Lebanon', 'Asia'),
 ('LR', 'Liberia', 'Africa'),
 ('LY', 'Libyan Arab Jamahiriya', 'Africa'),
 ('LC', 'Saint Lucia', 'North America'),
 ('LI', 'Liechtenstein', 'Europe'),
 ('LK', 'Sri Lanka', 'Asia'),
 ('LS', 'Lesotho', 'Africa'),
 ('LT', 'Lithuania', 'Europe'),
 ('LU', 'Luxembourg', 'Europe'),
 ('LV', 'Latvia', 'Europe'),
 ('MO', 'Macao', 'Asia'),
 ('MA', 'Morocco', 'Africa'),
 ('MC', 'Monaco', 'Europe'),
 ('MD', 'Moldova', 'Europe'),
 ('MG', 'Madagascar', 'Africa'),
 ('MV', 'Maldives', 'Asia'),
 ('MX', 'Mexico', 'North America'),
 ('MH', 'Marshall Islands', 'Oceania'),
 ('MK', 'Macedonia', 'Europe'),
 ('ML', 'Mali', 'Africa'),
 ('MT', 'Malta', 'Europe'),
 ('MM', 'Myanmar', 'Asia'),
 ('ME', 'Montenegro', 'Europe'),
 ('MN', 'Mongolia', 'Asia'),
 ('MP', 'Northern Mariana Islands', 'Oceania'),
 ('MZ', 'Mozambique', 'Africa'),
 ('MR', 'Mauritania', 'Africa'),
 ('MS', 'Montserrat', 'North America'),
 ('MQ', 'Martinique', 'North America'),
 ('MU', 'Mauritius', 'Africa'),
 ('MW', 'Malawi', 'Africa'),
 ('MY', 'Malaysia', 'Asia'),
 ('YT', 'Mayotte', 'Africa'),
 ('NA', 'Namibia', 'Africa'),
 ('NC', 'New Caledonia', 'Oceania'),
 ('NE', 'Niger', 'Africa'),
 ('NF', 'Norfolk Island', 'Oceania'),
 ('NG', 'Nigeria', 'Africa'),
 ('NI', 'Nicaragua', 'North America'),
 ('NU', 'Niue', 'Oceania'),
 ('NL', 'Netherlands', 'Europe'),
 ('NO', 'Norway', 'Europe'),
 ('NP', 'Nepal', 'Asia'),
 ('NR', 'Nauru', 'Oceania'),
 ('NZ', 'New Zealand', 'Oceania'),
 ('OM', 'Oman', 'Asia'),
 ('PK', 'Pakistan', 'Asia'),
 ('PA', 'Panama', 'North America'),
 ('PN', 'Pitcairn', 'Oceania'),
 ('PE', 'Peru', 'South America'),
 ('PH', 'Philippines', 'Asia'),
 ('PW', 'Palau', 'Oceania'),
 ('PG', 'Papua New Guinea', 'Oceania'),
 ('PL', 'Poland', 'Europe'),
 ('PR', 'Puerto Rico', 'North America'),
 ('KR', 'Korea', 'Asia'),
 ('PT', 'Portugal', 'Europe'),
 ('PY', 'Paraguay', 'South America'),
 ('PS', 'Palestinian Territory', 'Asia'),
 ('PF', 'French Polynesia', 'Oceania'),
 ('QA', 'Qatar', 'Asia'),
 ('RE', 'Reunion', 'Africa'),
 ('RO', 'Romania', 'Europe'),
 ('RU', 'Russian Federation', 'Asia'),
 ('RW', 'Rwanda', 'Africa'),
 ('SA', 'Saudi Arabia', 'Asia'),
 ('SD', 'Sudan', 'Africa'),
 ('SN', 'Senegal', 'Africa'),
 ('SG', 'Singapore', 'Asia'),
 ('GS', 'SouthGeorgiaAndTheSouthSandwichIsland', 'Antarctica'),
 ('SH', 'Saint Helena', 'Africa'),
 ('SJ', 'Svalbard and Jan Mayen', 'Europe'),
 ('SB', 'Solomon Islands', 'Oceania'),
 ('SL', 'Sierra Leone', 'Africa'),
 ('SV', 'El Salvador', 'North America'),
 ('SM', 'San Marino', 'Europe'),
 ('SO', 'Somalia', 'Africa'),
 ('PM', 'Saint Pierre and Miquelon', 'North America'),
 ('RS', 'Serbia', 'Europe'),
 ('ST', 'Sao Tome and Principe', 'Africa'),
 ('SR', 'Suriname', 'South America'),
 ('SK', 'Slovakia', 'Europe'),
 ('SI', 'Slovenia', 'Europe'),
 ('SE', 'Sweden', 'Europe'),
 ('SZ', 'Swaziland', 'Africa'),
 ('SC', 'Seychelles', 'Africa'),
 ('SY', 'Syrian', 'Asia'),
 ('TC', 'Turks and Caicos Islands', 'North America'),
 ('TD', 'Chad', 'Africa'),
 ('TG', 'Togo', 'Africa'),
 ('TH', 'Thailand', 'Asia'),
 ('TJ', 'Tajikistan', 'Asia'),
 ('TK', 'Tokelau', 'Oceania'),
 ('TM', 'Turkmenistan', 'Asia'),
 ('TL', 'Timor-Leste', 'Asia'),
 ('TO', 'Tonga', 'Oceania'),
 ('TT', 'Trinidad and Tobago', 'North America'),
 ('TN', 'Tunisia', 'Africa'),
 ('TR', 'Turkey', 'Asia'),
 ('TV', 'Tuvalu', 'Oceania'),
 ('TW', 'Taiwan', 'Asia'),
 ('TZ', 'Tanzania', 'Africa'),
 ('UG', 'Uganda', 'Africa'),
 ('UA', 'Ukraine', 'Europe'),
 ('UM', 'United States Minor Outlying Islands',
 'North America'),
 ('UY', 'Uruguay', 'South America'),
 ('US', 'United States', 'North America'),
 ('UZ', 'Uzbekistan', 'Asia'),
 ('VA', 'Vatican City State', 'Europe'),
 ('VC', 'Saint Vincent and the Grenadines', 'North America'),
 ('VE', 'Venezuela', 'South America'),
 ('VG', 'Virgin Islands British', 'North America'),
 ('VI', 'Virgin Islands US', 'North America'),
 ('VN', 'Viet Nam', 'Asia'),
 ('VU', 'Vanuatu', 'Oceania'),
 ('WF', 'Wallis and Futuna', 'Oceania'),
 ('WS', 'Samoa', 'Oceania'),
 ('YE', 'Yemen', 'Asia'),
 ('YU', 'Jugoslavija', 'Europe'),
 ('ZA', 'South Africa', 'Africa'),
 ('ZM', 'Zambia', 'Africa'),
 ('ZW', 'Zimbabwe', 'Africa');